"""empty message

Revision ID: 009b06b6936f
Revises: cf0796409da2
Create Date: 2024-01-19 19:10:34.386987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009b06b6936f'
down_revision = 'cf0796409da2'
branch_labels = None
depends_on = None

def upgrade():
    # Add the new column with a default value
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False, server_default='your_default_value'))

    # Update existing rows with a specific value for the new column
    op.execute('UPDATE "user" SET name = \'your_default_value\' WHERE name IS NULL')

    # Modify other columns as needed
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.String(length=200),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
