"""empty message

Revision ID: 7b9a3852b8b9
Revises: 9c9ec581cdeb
Create Date: 2024-01-29 19:36:32.533842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9a3852b8b9'
down_revision = '9c9ec581cdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ciudad', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ofertas', schema=None) as batch_op:
        batch_op.drop_column('Ciudad')

    # ### end Alembic commands ###
