"""empty message

Revision ID: 9c9ec581cdeb
Revises: 7916ff04d427
Create Date: 2024-01-24 18:28:47.887527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c9ec581cdeb'
down_revision = '7916ff04d427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administadores', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('admin', name='user_roles'), autoincrement=False, nullable=True))

    with op.batch_alter_table('administadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('admin', name='user_roles'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
