"""empty message

Revision ID: bf4e80c099a4
Revises: a4b5872fb74e
Create Date: 2024-01-15 19:38:52.456064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4e80c099a4'
down_revision = 'a4b5872fb74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TipoProyecto', sa.String(length=250), nullable=False),
    sa.Column('TipoEquipo', sa.String(length=250), nullable=False),
    sa.Column('Pais', sa.String(length=250), nullable=False),
    sa.Column('FechaOferta', sa.DateTime(), nullable=False),
    sa.Column('Precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ofertas')
    # ### end Alembic commands ###
